all:
	/u/a/r/araina/private/CS752/risc5_ooo/riscv-tools/bin/riscv64-unknown-elf-gcc -m64 -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -I/u/a/r/araina/private/CS752/risc5_ooo/riscv-tools/riscv-tests/build/../isa/../env/p -I/u/a/r/araina/private/CS752/risc5_ooo/riscv-tools/riscv-tests/build/../isa/macros/scalar -T/u/a/r/araina/private/CS752/risc5_ooo/riscv-tools/riscv-tests/build/../isa/../env/p/link.ld /u/a/r/araina/private/CS752/risc5_ooo/riscv-tools/riscv-tests/build/../isa/rv64ui/lh.S -o r64ui-p-lh

